name: absensi
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  camera: ^0.10.5+9
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  google_mlkit_face_detection: ^0.5.0
  cloud_firestore: ^5.4.4
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.6
  lottie: ^3.1.0
  http: ^1.2.1
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  share_plus: ^2.0.0
  file_picker: ^8.1.4
  image_picker: ^1.0.0
  image_picker_for_web: ^2.0.0
  shared_preferences: ^2.1.1
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/raw/
    - assets/images/ic_absen.png
    - assets/images/ic_history.png
    - assets/images/ic_leave.png
