// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi5-BaJwt1GQZRylMUxeBRkWHi6X1unhA',
    appId: '1:846956450434:web:65962aeb7b8dba20b75a9b',
    messagingSenderId: '846956450434',
    projectId: 'absensi-703d7',
    authDomain: 'absensi-703d7.firebaseapp.com',
    storageBucket: 'absensi-703d7.firebasestorage.app',
    measurementId: 'G-ZV25PE70HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZtl0jiLMHp6-fSXLKA3zNZjMovIZZoQ',
    appId: '1:846956450434:android:75cd847e157e1f2cb75a9b',
    messagingSenderId: '846956450434',
    projectId: 'absensi-703d7',
    storageBucket: 'absensi-703d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkUGUJZM7oxf7RFIIE9yy2KOxavd7pXog',
    appId: '1:846956450434:ios:ae6f84f3e70972ddb75a9b',
    messagingSenderId: '846956450434',
    projectId: 'absensi-703d7',
    storageBucket: 'absensi-703d7.firebasestorage.app',
    iosBundleId: 'com.example.absensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkUGUJZM7oxf7RFIIE9yy2KOxavd7pXog',
    appId: '1:846956450434:ios:ae6f84f3e70972ddb75a9b',
    messagingSenderId: '846956450434',
    projectId: 'absensi-703d7',
    storageBucket: 'absensi-703d7.firebasestorage.app',
    iosBundleId: 'com.example.absensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi5-BaJwt1GQZRylMUxeBRkWHi6X1unhA',
    appId: '1:846956450434:web:7ff4f0fbcf944324b75a9b',
    messagingSenderId: '846956450434',
    projectId: 'absensi-703d7',
    authDomain: 'absensi-703d7.firebaseapp.com',
    storageBucket: 'absensi-703d7.firebasestorage.app',
    measurementId: 'G-3LH9LH7L0X',
  );

  static var current;
}
